[package]
name = "xrpl"
version = "0.0.1"
edition = "2021"

[dependencies]
base58check = "0.1.0"
#derive = "1.0.0"
derive_more = "0.99.17"
serde_json = "1.0.93"
lazy_static = "1.4.0"
async-trait = "0.1.64"
reqwest = { version = "0.11.14", features = ["json"] }
workflow-websocket = "0.3.10"
fragile = "2.0.0"
